language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=psr2 src test

after_success:
  - php vendor/bin/php-coveralls
